### PR TITLE
Upgrade to Sync v0.6, use the default instance.

### PR DESCRIPTION
**Pull request by ajtack**
This PR also (I think) fixes a syntax error (some difference among python versions?). Maybe needs a look-over from a Python person.

### CODE REVIEW

**Comment by jefflinwood** [comment]
Which Python version were you using locally to test it? Thanks!

**Comment by ajtack** [comment]
Python 3.6.1

**Comment by jefflinwood** [comment]
Thanks! I see the same exact problem with Python 3.6.3. Thanks for the fix (which I'll also test against Python 2)

**Comment by jefflinwood** [comment]
Ok, that fix breaks in Python 2. I'll see what I can do about making a fix that works on both.

**Comment by jefflinwood** [comment]
I'll merge in this pull request, then create a new PR with a fix for Python 2 and Python 3

**Pull request merged**
